---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: test-renovate
  namespace: jcapitao-redhat-com-tenant
  annotations:
    application.thumbnail: "1"
spec:
  displayName: "test-renovate"
