---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: test-renovate
  namespace: jcapitao-redhat-com-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: github.com
spec:
  application: test-renovate
  componentName: test-renovate
  source:
    git:
      url: https://github.com/jcapiitao/test-renovate.git
      revision: main
      context: ./
      dockerfileUrl: Dockerfile
  containerImage: quay.io/konflux-fedora/jcapitao-redhat-com-tenant/test-renovate
