---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-test-renovate
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: test-renovate
    appstudio.redhat.com/component: test-renovate
spec:
  image:
    name: jcapitao-redhat-com-tenant/test-renovate
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
