apiVersion: appstudio.redhat.com/v1alpha1
kind: Component 
metadata:
  name: cosa-jcapitao
  namespace: coreos-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}' 
    git-provider: github 
    git-provider-url: github.com
spec:
  application: fcos-jcapitao
  componentName: cosa-jcapitao
  source:
    git:
      url: https://github.com/jcapiitao/cosa.git
      revision: main
      context: ./ 
      dockerfileUrl: Dockerfile
  containerImage: quay.io/konflux-fedora/coreos-tenant/cosa-jcapitao
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository 
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-fcos-cosa-jcapitao
  namespace: coreos-tenant
  labels:
    appstudio.redhat.com/application: fcos-jcapitao
    appstudio.redhat.com/component: cosa-jcapitao
spec:
  image:
    name: coreos-tenant/cosa-jcapitao
    visibility: public 
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
