apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/fcos-pipeline-jcapitao.yaml
  - components/cosa-jcapitao.yaml
  - image_repository/imagerepository-for-fcos-cosa-jcapitao.yaml
namespace: coreos-tenant
