---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: test-renovate2
  namespace: coreos-tenant
  annotations:
    application.thumbnail: "1"
spec:
  displayName: "test-renovate2-jcapitao"
