---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-test-renovate2
  namespace: coreos-tenant
  labels:
    appstudio.redhat.com/application: test-renovate2
    appstudio.redhat.com/component: test-renovate2
spec:
  image:
    name: coreos-tenant/test-renovate2
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
