---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: coreos-assembler-jcapitao
  namespace: jcapitao-redhat-com-tenant
  annotations:
    application.thumbnail: "1"
spec:
  displayName: "coreos-assembler-jcapitao"
