---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: coreos-assembler-jcapitao
  namespace: coreos-tenant
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: github.com
spec:
  application: coreos-assembler-jcapitao
  componentName: coreos-assembler-jcapitao
  source:
    git:
      url: https://github.com/jcapiitao/coreos-assembler.git
      revision: konflux
      context: ./
      dockerfileUrl: Dockerfile
  containerImage: quay.io/redhat-user-workloads/coreos-tenant/coreos-assembler-jcapitao
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: kola-nfs-jcapitao
  namespace: coreos-tenant
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: github.com
spec:
  application: coreos-assembler-jcapitao
  componentName: kola-nfs-jcapitao
  source:
    git:
      url: https://github.com/jcapiitao/coreos-assembler.git
      revision: konflux
      context: ./tests/containers/nfs
      dockerfileUrl: Containerfile
  containerImage: quay.io/redhat-user-workloads/coreos-tenant/kola-nfs-jcapitao
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: kola-tang-jcapitao
  namespace: coreos-tenant
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: github.com
spec:
  application: coreos-assembler-jcapitao
  componentName: kola-tang-jcapitao
  source:
    git:
      url: https://github.com/jcapiitao/coreos-assembler.git
      revision: konflux
      context: ./tests/containers/tang
      dockerfileUrl: Containerfile
  containerImage: quay.io/redhat-user-workloads/coreos-tenant/kola-tang-jcapitao
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: kola-targetcli-jcapitao
  namespace: coreos-tenant
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: github.com
spec:
  application: coreos-assembler-jcapitao
  componentName: kola-targetcli-jcapitao
  source:
    git:
      url: https://github.com/jcapiitao/coreos-assembler.git
      revision: konflux
      context: ./tests/containers/targetcli
      dockerfileUrl: Containerfile
  containerImage: quay.io/redhat-user-workloads/coreos-tenant/kola-targetcli-jcapitao
