---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-coreos-assembler-jcapitao
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler-jcapitao
    appstudio.redhat.com/component: coreos-assembler-jcapitao
spec:
  image:
    name: coreos-tenant/coreos-assembler-jcapitao
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-kola-nfs-jcapitao
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler-jcapitao
    appstudio.redhat.com/component: kola-nfs-jcapitao
spec:
  image:
    name: coreos-tenant/kola-nfs-jcapitao
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-kola-tang-jcapitao
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler-jcapitao
    appstudio.redhat.com/component: kola-tang-jcapitao
spec:
  image:
    name: coreos-tenant/kola-tang-jcapitao
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-kola-targetcli-jcapitao
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler-jcapitao
    appstudio.redhat.com/component: kola-targetcli-jcapitao
spec:
  image:
    name: coreos-tenant/kola-targetcli-jcapitao
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
