---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-coreos-assembler
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler
    appstudio.redhat.com/component: coreos-assembler
spec:
  image:
    name: jcapitao-redhat-com-tenant/coreos-assembler
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-kola-nfs
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler
    appstudio.redhat.com/component: kola-nfs
spec:
  image:
    name: jcapitao-redhat-com-tenant/kola-nfs
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-kola-tang
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler
    appstudio.redhat.com/component: kola-tang
spec:
  image:
    name: jcapitao-redhat-com-tenant/kola-tang
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-kola-targetcli
  namespace: jcapitao-redhat-com-tenant
  labels:
    appstudio.redhat.com/application: coreos-assembler
    appstudio.redhat.com/component: kola-targetcli
spec:
  image:
    name: jcapitao-redhat-com-tenant/kola-targetcli
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
