apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - components.yaml
  - devstream.yaml
  - image-repository.yaml
  - project.yaml
  - template.yaml
namespace: jcapitao-redhat-com-tenant
