apiVersion: projctl.konflux.dev/v1beta1
kind: Project
metadata:
  name: coreos-assembler
spec:
  displayName: "coreos-assembler"
  description: |
    This projects aims to build https://github.com/coreos/coreos-assembler/
