---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: imagerepository-for-tekton-task-cosa-build-jcapitao
  namespace: coreos-tenant
  labels:
    appstudio.redhat.com/application: fedora-coreos-pipeline-jcapitao
    appstudio.redhat.com/component: tekton-task-cosa-build-jcapitao
spec:
  image:
    name: coreos-tenant/tekton-task-cosa-build-jcapitao
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
