name: Schedule test on Testing Farm
on:
  pull_request:

concurrency:
  group: my-concurrency-group
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule test on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v4
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          secrets: SMEE_WEBHOOK_SECRET=${{ secrets.SMEE_WEBHOOK_SECRET }};QUAY_KONFLUX_APP_TOKEN=${{ secrets.QUAY_KONFLUX_APP_TOKEN }}
